/* Generated By:JavaCC: Do not edit this line. BasicParserConstants.java */
package parser;

public interface BasicParserConstants {

  int EOF = 0;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
