/* Generated By:JJTree: Do not edit this line. ASTOptions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTOptions extends JJTreeNode
{
  public ASTOptions (final int id)
  {
    super (id);
  }

  public ASTOptions (final JJTreeParser p, final int id)
  {
    super (p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept (final JJTreeParserVisitor visitor, final Object data)
  {
    return visitor.visit (this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=30aa49e720b353fc345932a3b397455a (do not edit this
 * line)
 */
