/* Generated By:JavaCC: Do not edit this line. JJTreeParserVisitor.java Version 4.1d1 */
package org.javacc.jjtree;

public class DefaultJJTreeVisitor implements JJTreeParserVisitor
{
  public Object defaultVisit (final SimpleNode node, final Object data)
  {
    return node.childrenAccept (this, data);
  }

  public Object visit (final SimpleNode node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTGrammar node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTCompilationUnit node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTProductions node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTOptions node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTOptionBinding node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTJavacode node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTJavacodeBody node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNF node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFDeclaration node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFNodeScope node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRE node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTTokenDecls node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRESpec node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFChoice node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFSequence node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFLookahead node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTExpansionNodeScope node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFAction node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFZeroOrOne node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFTryBlock node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFNonTerminal node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFAssignment node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFOneOrMore node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFZeroOrMore node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTBNFParenthesized node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREStringLiteral node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRENamed node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREReference node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREEOF node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREChoice node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRESequence node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREOneOrMore node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREZeroOrMore node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREZeroOrOne node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRRepetitionRange node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTREParenthesized node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTRECharList node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTCharDescriptor node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTNodeDescriptor node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTNodeDescriptorExpression node, final Object data)
  {
    return defaultVisit (node, data);
  }

  public Object visit (final ASTPrimaryExpression node, final Object data)
  {
    return defaultVisit (node, data);
  }
}
/*
 * JavaCC - OriginalChecksum=3b7689ed0de9c57e70ae4a27c1480635 (do not edit this
 * line)
 */
